token:
  expiration_time: 864000000
  secret: '{cipher}AQASc+Jmv2p7dqi/BO+MSCsTzfCIard2J4TJDladsqRoHn+Qxuk06H54pkIrMTf+msDLXSmL9uOjoSiwcDOLecNMf7zq4DMEPX4ZyixB9jscGegTWD3KluUCWA5435z2LfBuhWyWuOn9TfvvO9MH6qVIqStHOiS19hO3dtvUZgqffwJhQgjGrRpS8NV2gChdKsE5FVbewwvDR2X05dsspkoMnVNkFc9lRqVCKt8NZuOlrBqsP+bYm7g5Cw+Z4bEqadp4RUPAnBgRBLoBdS7e8Oiqranx6SUD+rZ/aKrA5l3p/osZXnDqKOfy7vmQCobiyGutfPcavxrAKy/pJMCU8V4WOc9p74Hku7fSOVzRMcslC3eDo+h0Jlj9mjYPjmIrQk8kihO0jk7qi2ZNd8FQKgjl'

gateway:
  ip: 192.168.0.21